CL SCR;

/* All backups and recoveries are performed directly on the root container
 *  database (CDB) XE. Certainly should not enact this file if your XE has
 *  a lot of PDBs and data.
 * Despite only using XEPDB1, the above drastic approach is taken because
 *  of the absolute hurdle of solely interacting with a PDB, without the
 *  backing up or recovering of the CDB, due to mismatched metadata.
 *  E.g., https://www.pythian.com/blog/restoring-a-dropped-oracle-pdb-without-a-cdb-backup
 *
 * All commented-out commands, lacking any symbol before them, are supposed
 *  to be run in the console. Unless stated otherwise, by the appearance of
 *  "SQLPLUS" or "WINDOWS", all commands are to be executed under RMAN
 *  connection to XE using OS authentication, i.e., RMAN TARGET / .
 *
 * Need to put the database into ARCHIVELOG mode beforehand. All the TAG and
 *  SCN numbers should be replaced, by looking them up in the LIST BACKUP and
 *  audit trail. Also, every FORMAT clause is optional.
 */

/*          ---- HANDIES ----
-- SWITCH DATABASE TO ARCHIVELOG MODE
SQLPLUS / AS SYSDBA
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

-- CHECK OPEN MODE OF CURRENT DATABASE
SELECT INSTANCE_NAME, STATUS, DATABASE_STATUS, INSTANCE_ROLE from V$INSTANCE;
-- CHECK OPEN MODE OF PDBS
SELECT NAME, OPEN_MODE FROM V$PDBS;

-- CONNECT RMAN USING OS AUTH
RMAN TARGET /
-- CHECKING BACKUPS
LIST BACKUP OF DATABASE SUMMARY;
LIST BACKUP OF CONTROLFILE;

-- SEE ALL CONFIGURE PARAMETERS
SHOW ALL;
-- TURN CONTROLFILE AUTOBACKUP ON
CONFIGURE CONTROLFILE AUTOBACKUP ON;
 */

/*          ---- FULL BACKUP AND RECOVERY ----
-- CREATE FULL BACKUP
BACKUP DATABASE PLUS ARCHIVELOG FORMAT 'D:/OraBkps/fullbkp_%u';
 */
-- CREATE DUMMY UPDATES
CONN V20062/123@LOCALHOST:1521/XEPDB1;
SELECT * FROM A01_QLNOIBO.V_DANGKY_V WHERE MASV = 'S10081'; -- 6.95
UPDATE A01_QLNOIBO.V_DANGKY_V SET DIEMTH = 8    -- Intended
WHERE MASV = 'S10081' AND MAHP = '110012';
UPDATE A01_QLNOIBO.V_DANGKY_V SET DIEMTH = 9    -- Accidental
WHERE MASV = 'S10081' AND MAHP = '110012';      -- Rollback needed
SELECT * FROM A01_QLNOIBO.V_DANGKY_V WHERE MASV = 'S10081'; -- 9

-- TAKE NOTE OF THE SCN OF THE SECOND UPDATE
CONN AD0001/123@LOCALHOST:1521/XEPDB1;
SELECT AUDIT_TYPE, DBUSERNAME, EVENT_TIMESTAMP, SCN, ACTION_NAME, OBJECT_SCHEMA,
    OBJECT_NAME, SQL_TEXT, UNIFIED_AUDIT_POLICIES FROM UNIFIED_AUDIT_TRAIL
WHERE AUDIT_TYPE = 'Standard' AND DBUSERNAME = 'V20062'
    AND UNIFIED_AUDIT_POLICIES LIKE '%AUDPOL_GENERAL%'
ORDER BY EVENT_TIMESTAMP;

/*-- PERFORM PITR (INCOMPLETE RECOVERY)
 * Revert back to before the second update by using its scn.
 * The TAG can be found by LIST BACKUP OF DATABASE SUMMARY;. Could just
 *  use RESTORE DATABASE; if there was only a single backup.
 * The UNTIL SCN clause won't actually include the given scn.
RUN {
    SHUTDOWN IMMEDIATE;
    STARTUP MOUNT;
    SET UNTIL SCN 6163547;
    RESTORE DATABASE FROM TAG TAG20240401T205847;
    RECOVER DATABASE;
    ALTER DATABASE OPEN RESETLOGS;
}
 */
-- Now we should see DIEMTH = 8, and the last entry (second update) has
--  been removed from the audit trail.
CONN V20062/123@LOCALHOST:1521/XEPDB1;
SELECT * FROM A01_QLNOIBO.V_DANGKY_V WHERE MASV = 'S10081';
CONN AD0001/123@LOCALHOST:1521/XEPDB1;
SELECT AUDIT_TYPE, DBUSERNAME, EVENT_TIMESTAMP, SCN, ACTION_NAME, OBJECT_SCHEMA,
    OBJECT_NAME, SQL_TEXT, UNIFIED_AUDIT_POLICIES FROM UNIFIED_AUDIT_TRAIL
WHERE AUDIT_TYPE = 'Standard' AND DBUSERNAME = 'V20062'
    AND UNIFIED_AUDIT_POLICIES LIKE '%AUDPOL_GENERAL%'
ORDER BY EVENT_TIMESTAMP;

/*-- SIMULATE FAILURES
 * Try deleting control files and datafiles of XE and XEPDB1.
-- WINDOWS DELETE COMMANDS
del "D:\ORACLE21C\ORADATA\XE\CONTROL*"
del "D:\ORACLE21C\ORADATA\XE\SYS*"
del "D:\ORACLE21C\ORADATA\XE\UND*"
del "D:\ORACLE21C\ORADATA\XE\USER*"
 */
SELECT "NAME" FROM V$CONTROLFILE;
SELECT "NAME" FROM V$DATAFILE;

/*-- RESTORING CONTROL FILES AND MOUNT DATABASE
 * Skip this step if didn't delete control files.
 * Find control files backup by LIST BACKUP OF CONTROLFILE;
RUN {
    RESTORE CONTROLFILE FROM 'D:\ORACLE21C\DBHOMEXE\DATABASE\C-3046039191-20240401-03';
    ALTER DATABASE MOUNT;
}

-- PERFORM COMPLETE RECOVERY
 * Nothing should change when try to query V_DANGKY_V as V20062, and audit
 *  trail again after the recovery.
RUN {
    SHUTDOWN IMMEDIATE;
    STARTUP MOUNT;
    RESTORE DATABASE FROM TAG TAG20240401T205847;
    RECOVER DATABASE;
    ALTER DATABASE OPEN;
}
 */

/*          ---- INCREMENTAL DIFFERENTIAL BACKUP AND RECOVERY ----
-- CREATE LEVEL 0 BACKUP
BACKUP INCREMENTAL LEVEL 0 DATABASE PLUS ARCHIVELOG FORMAT 'D:/OraBkps/incbkp_%u';
 */
-- CREATE DUMMY UPDATE U#1
CONN V20062/123@LOCALHOST:1521/XEPDB1;
UPDATE A01_QLNOIBO.V_DANGKY_V SET DIEMTH = 7
WHERE MASV = 'S10081' AND MAHP = '110012';
CONN AD0001/123@LOCALHOST:1521/XEPDB1;
SELECT AUDIT_TYPE, DBUSERNAME, EVENT_TIMESTAMP, SCN, ACTION_NAME, OBJECT_SCHEMA,
    OBJECT_NAME, SQL_TEXT, UNIFIED_AUDIT_POLICIES FROM UNIFIED_AUDIT_TRAIL
WHERE AUDIT_TYPE = 'Standard' AND DBUSERNAME = 'V20062'
    AND UNIFIED_AUDIT_POLICIES LIKE '%AUDPOL_GENERAL%'
ORDER BY EVENT_TIMESTAMP;
/*-- CREATE LEVEL 1 BACKUP B#1
BACKUP INCREMENTAL LEVEL 1 DATABASE PLUS ARCHIVELOG FORMAT 'D:/OraBkps/incbkp_%u';
 */
-- CREATE DUMMY UPDATE U#2
CONN V20062/123@LOCALHOST:1521/XEPDB1;
UPDATE A01_QLNOIBO.V_DANGKY_V SET DIEMTH = 6.95
WHERE MASV = 'S10081' AND MAHP = '110012';
CONN AD0001/123@LOCALHOST:1521/XEPDB1;
SELECT AUDIT_TYPE, DBUSERNAME, EVENT_TIMESTAMP, SCN, ACTION_NAME, OBJECT_SCHEMA,
    OBJECT_NAME, SQL_TEXT, UNIFIED_AUDIT_POLICIES FROM UNIFIED_AUDIT_TRAIL
WHERE AUDIT_TYPE = 'Standard' AND DBUSERNAME = 'V20062'
    AND UNIFIED_AUDIT_POLICIES LIKE '%AUDPOL_GENERAL%'
ORDER BY EVENT_TIMESTAMP;
/*-- CREATE LEVEL 1 BACKUP B#2
BACKUP INCREMENTAL LEVEL 1 DATABASE PLUS ARCHIVELOG FORMAT 'D:/OraBkps/incbkp_%u';
 */
-- CREATE DUMMY UPDATE U#3
CONN V20062/123@LOCALHOST:1521/XEPDB1;
UPDATE A01_QLNOIBO.V_DANGKY_V SET DIEMTH = 5
WHERE MASV = 'S10081' AND MAHP = '110012';
CONN AD0001/123@LOCALHOST:1521/XEPDB1;
SELECT AUDIT_TYPE, DBUSERNAME, EVENT_TIMESTAMP, SCN, ACTION_NAME, OBJECT_SCHEMA,
    OBJECT_NAME, SQL_TEXT, UNIFIED_AUDIT_POLICIES FROM UNIFIED_AUDIT_TRAIL
WHERE AUDIT_TYPE = 'Standard' AND DBUSERNAME = 'V20062'
    AND UNIFIED_AUDIT_POLICIES LIKE '%AUDPOL_GENERAL%'
ORDER BY EVENT_TIMESTAMP;

/*-- PERFORM COMPLETE RECOVERY
 * Could SIMULATE FAILURES after U#3.
 * RECOVER CONTROLFILE if deleted during failures.
 * RESTORE DATABASE FROM TAG of the level 0 backup.
 * RECOVER DATABASE FROM TAG of the B#1 backup, now at U#1.
 * RECOVER DATABASE FROM TAG of the B#2 backup, now at U#2.
 * RECOVER DATABASE by applying logs to reach U#3.
RUN {
    SHUTDOWN IMMEDIATE;
    STARTUP MOUNT;
    RESTORE DATABASE FROM TAG TAG20240401T224748;
    RECOVER DATABASE FROM TAG TAG20240401T224952;
    RECOVER DATABASE FROM TAG TAG20240401T225142;
    RECOVER DATABASE;
    ALTER DATABASE OPEN;
}
 */
-- Note that even though a level 1 backup wasn't taken after U#3, we were
--  still able to apply redo logs on top of B#2 to reach the present point.
CONN V20062/123@LOCALHOST:1521/XEPDB1;
SELECT * FROM A01_QLNOIBO.V_DANGKY_V WHERE MASV = 'S10081';
CONN AD0001/123@LOCALHOST:1521/XEPDB1;
SELECT AUDIT_TYPE, DBUSERNAME, EVENT_TIMESTAMP, SCN, ACTION_NAME, OBJECT_SCHEMA,
    OBJECT_NAME, SQL_TEXT, UNIFIED_AUDIT_POLICIES FROM UNIFIED_AUDIT_TRAIL
WHERE AUDIT_TYPE = 'Standard' AND DBUSERNAME = 'V20062'
    AND UNIFIED_AUDIT_POLICIES LIKE '%AUDPOL_GENERAL%'
ORDER BY EVENT_TIMESTAMP;

/*-- PERFORM PITR (INCOMPLETE RECOVERY)
 * Let us only recover upto U#2, discarding U#3.
 * Querying the two upper SELECTs after should then show DIEMTH = 6.95, and
 *  the instance of U#3 missing from the audit trail.
 * The SCN belongs to u#3, look it up in the audit trail.
RUN {
    SHUTDOWN IMMEDIATE;
    STARTUP MOUNT;
    SET UNTIL SCN 6166184;
    RESTORE DATABASE FROM TAG TAG20240401T224748;
    RECOVER DATABASE FROM TAG TAG20240401T224952;
    RECOVER DATABASE FROM TAG TAG20240401T225142;
    RECOVER DATABASE;
    ALTER DATABASE OPEN RESETLOGS;
}
 */