CL SCR;
CONN AD0001/123@LOCALHOST:1521/XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = A01_QLNOIBO;

NOAUDIT POLICY AUDPOL_GENERAL; DROP AUDIT POLICY AUDPOL_GENERAL;
NOAUDIT POLICY AUDPOL_GENERAL_USP BY TK0001 WHENEVER NOT SUCCESSFUL;
DROP AUDIT POLICY AUDPOL_GENERAL_USP;

BEGIN SA_SYSDBA.DROP_POLICY(
    POLICY_NAME  => 'POL_A01_THONGBAO',
    DROP_COLUMN  => FALSE
); END;
/

CONN SYS@LOCALHOST:1521/XEPDB1 AS SYSDBA;
ALTER SESSION SET CURRENT_SCHEMA = A01_QLNOIBO;

DECLARE CUR SYS_REFCURSOR; STR VARCHAR2(100);
BEGIN
    OPEN CUR FOR SELECT 'ALTER SYSTEM KILL SESSION ''' || SID || ','
        || SERIAL# || '''' FROM V$SESSION WHERE USERNAME = 'AD0001';
    LOOP FETCH CUR INTO STR; EXIT WHEN CUR%NOTFOUND;
        EXECUTE IMMEDIATE STR;
    END LOOP; CLOSE CUR;
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
    WHEN OTHERS THEN RAISE;
END;
/
DROP USER AD0001;

CREATE OR REPLACE PROCEDURE USP_DROP_USERS
AS
    CURSOR CUR_NHANSU IS (SELECT MANV FROM NHANSU
        WHERE MANV IN (SELECT USERNAME FROM ALL_USERS));
    CURSOR CUR_SINHVIEN IS (SELECT MASV FROM SINHVIEN
        WHERE MASV IN (SELECT USERNAME FROM ALL_USERS));
BEGIN
    FOR USR IN CUR_NHANSU LOOP
        EXECUTE IMMEDIATE 'DROP USER ' || USR.MANV;
    END LOOP;
    FOR USR IN CUR_SINHVIEN LOOP
        EXECUTE IMMEDIATE 'DROP USER ' || USR.MASV;
    END LOOP;
END;
/
EXEC USP_DROP_USERS();

ALTER SESSION SET CURRENT_SCHEMA = SYS;
CREATE OR REPLACE PROCEDURE USP_DROP_ROLES
AS
    CURSOR CUR IS (SELECT "ROLE" AS RO FROM DBA_ROLES
        WHERE "ROLE" LIKE 'RL_A01%');
BEGIN
    FOR RL IN CUR LOOP
        EXECUTE IMMEDIATE 'DROP ROLE ' || RL.RO;
    END LOOP;
END;
/
EXEC USP_DROP_ROLES();
DROP PROCEDURE USP_DROP_ROLES;

DROP USER A01_QLNOIBO CASCADE;