CL SCR;
CONN AD0001/123@LOCALHOST:1521/XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = A01_QLNOIBO;

BEGIN SA_SYSDBA.DROP_POLICY(
    POLICY_NAME  => 'POL_A01_THONGBAO',
    DROP_COLUMN  => FALSE
); END;
/

CONN SYS@LOCALHOST:1521/XEPDB1 AS SYSDBA;
ALTER SESSION SET CURRENT_SCHEMA = A01_QLNOIBO;

DECLARE STR VARCHAR2(100);
BEGIN
    SELECT 'ALTER SYSTEM KILL SESSION ''' || SID || ','
        || SERIAL# || '''' INTO STR
    FROM V$SESSION WHERE USERNAME = 'AD0001';
    EXECUTE IMMEDIATE STR;
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
    WHEN OTHERS THEN RAISE;
END;
/
DROP USER AD0001;

CREATE OR REPLACE PROCEDURE USP_DROP_USERS
AS
    CURSOR CUR_NHANSU IS (SELECT MANV FROM NHANSU
        WHERE MANV IN (SELECT USERNAME FROM ALL_USERS));
    CURSOR CUR_SINHVIEN IS (SELECT MASV FROM SINHVIEN
        WHERE MASV IN (SELECT USERNAME FROM ALL_USERS));
BEGIN
    FOR USR IN CUR_NHANSU LOOP
        EXECUTE IMMEDIATE 'DROP USER ' || USR.MANV;
    END LOOP;
    FOR USR IN CUR_SINHVIEN LOOP
        EXECUTE IMMEDIATE 'DROP USER ' || USR.MASV;
    END LOOP;
END;
/
EXEC USP_DROP_USERS();

ALTER SESSION SET CURRENT_SCHEMA = SYS;
CREATE OR REPLACE PROCEDURE USP_DROP_ROLES
AS
    CURSOR CUR IS (SELECT "ROLE" AS RO FROM DBA_ROLES
        WHERE "ROLE" LIKE 'RL_A01%');
BEGIN
    FOR RL IN CUR LOOP
        EXECUTE IMMEDIATE 'DROP ROLE ' || RL.RO;
    END LOOP;
END;
/
EXEC USP_DROP_ROLES();
DROP PROCEDURE USP_DROP_ROLES;

DROP USER A01_QLNOIBO CASCADE;

/* LEGACY
 */
--      ---- CS2: GIANG VIEN ----
-- CREATE OR REPLACE VIEW V_PHANCONG_V
-- AS SELECT * FROM PHANCONG
--     WHERE MAGV = SYS_CONTEXT('USERENV', 'SESSION_USER');

-- GRANT SELECT ON V_PHANCONG_V TO RL_A01_V;

--      ---- CS3: GIAO VU ----
-- CREATE OR REPLACE VIEW V_PHANCONG_GV
-- AS SELECT * FROM PHANCONG;

-- CREATE OR REPLACE FUNCTION PFN_V_PHANCONG_GV(
--     P_SCHEMA VARCHAR2, P_OBJ VARCHAR2
-- ) RETURN VARCHAR2 AS BEGIN
--     RETURN 'MAHP IN (SELECT MAHP FROM HOCPHAN WHERE MADV = 1)';
-- END;
-- /

-- BEGIN DBMS_RLS.ADD_POLICY(
--     OBJECT_SCHEMA  => 'A01_QLNOIBO',
--     OBJECT_NAME  => 'V_PHANCONG_GV',
--     POLICY_NAME  => 'POL_V_PHANCONG_GV',
--     FUNCTION_SCHEMA  => 'A01_QLNOIBO',
--     POLICY_FUNCTION  => 'PFN_V_PHANCONG_GV',
--     STATEMENT_TYPES  => 'UPDATE',
--     UPDATE_CHECK => TRUE
-- ); END;
-- /

-- GRANT SELECT, UPDATE ON V_PHANCONG_GV TO RL_A01_GV;

--      ---- CS3: GIAO VU ----
-- CREATE OR REPLACE VIEW V_DANGKY_GV
-- AS SELECT * FROM DANGKY;

-- CREATE OR REPLACE FUNCTION PFN_V_DANGKY_GV(
--     P_SCHEMA VARCHAR2, P_OBJ VARCHAR2
-- ) RETURN VARCHAR2 AS
--     DIFF FLOAT; HK CHAR(1);
--     MO NUMBER(2) := TO_NUMBER(TO_CHAR(SYSDATE, 'MM'));
--     YE NUMBER(4) := TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'));
-- BEGIN
--     IF MO < 5 THEN HK := '1';
--         DIFF :=  SYSDATE - TO_DATE('01/01' || YE, 'DD/MM/YYYY');
--     ELSIF MO < 9 THEN HK := '2';
--         DIFF :=  SYSDATE - TO_DATE('01/05' || YE, 'DD/MM/YYYY');
--     ELSE HK := '3';
--         DIFF :=  SYSDATE - TO_DATE('01/09' || YE, 'DD/MM/YYYY');
--     END IF;
--     RETURN 'HK = ' || HK || ' AND NAM = ' || YE
--         || 'AND 0 < ' || DIFF || ' AND ' || DIFF || '<= 14';
-- END;
-- /

-- BEGIN DBMS_RLS.ADD_POLICY(
--     OBJECT_SCHEMA  => 'A01_QLNOIBO',
--     OBJECT_NAME  => 'V_DANGKY_GV',
--     POLICY_NAME  => 'POL_V_DANGKY_GV',
--     FUNCTION_SCHEMA  => 'A01_QLNOIBO',
--     POLICY_FUNCTION  => 'PFN_V_DANGKY_GV',
--     STATEMENT_TYPES  => 'INSERT, DELETE',
--     UPDATE_CHECK => TRUE
-- ); END;
-- /

-- GRANT SELECT, INSERT, DELETE ON V_DANGKY_GV TO RL_A01_GV;

--      ---- CS3: GIAO VU ----
-- CREATE OR REPLACE TRIGGER TR_V_DANGKY_GV_INS
--     BEFORE INSERT OR DELETE ON V_DANGKY_GV
--     FOR EACH ROW
-- DECLARE
--     DIFF FLOAT;
--     MO NUMBER(2) := TO_NUMBER(TO_CHAR(SYSDATE, 'MM'));
--     YE NUMBER(4) := TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'));
-- BEGIN
-- IF INSERTING THEN
--     IF :NEW.HK = '1' THEN DIFF := SYSDATE - TO_DATE('01/03' || YE, 'DD/MM/YYYY');
--     ELSIF :NEW.HK = '2' THEN DIFF := SYSDATE - TO_DATE('01/05' || YE, 'DD/MM/YYYY');
--     ELSE DIFF := SYSDATE - TO_DATE('01/09' || YE, 'DD/MM/YYYY');
--     END IF;
-- ELSIF DELETING THEN
--     IF :OLD.HK = '1' THEN DIFF := SYSDATE - TO_DATE('01/03' || YE, 'DD/MM/YYYY');
--     ELSIF :OLD.HK = '2' THEN DIFF := SYSDATE - TO_DATE('01/05' || YE, 'DD/MM/YYYY');
--     ELSE DIFF := SYSDATE - TO_DATE('01/09' || YE, 'DD/MM/YYYY');
--     END IF;
-- END IF;
--     IF DIFF < 0 OR DIFF > 14 THEN
--         RAISE_APPLICAION_ERROR(-20000, 'MORE THAN 14 DAYS HAVE PASSED SINCE THE START OF THE SEMESTER!')
--     END IF;
-- END;
-- /

--      ---- CS4: TRUONG DON VI ----
-- CREATE OR REPLACE VIEW V_PHANCONG_TD
-- AS SELECT * FROM PHANCONG;

-- CREATE OR REPLACE FUNCTION PFN_V_PHANCONG_TD(
--     P_SCHEMA VARCHAR2, P_OBJ VARCHAR2
-- ) RETURN VARCHAR2 AS
-- BEGIN
--     RETURN 'MAHP IN (SELECT MAHP FROM HOCPHAN
--         WHERE MADV = (SELECT MADV FROM NHANSU
--             WHERE MANV = ''' || SYS_CONTEXT('USERENV', 'SESSION_USER') || '''))';
-- END;
-- /

-- BEGIN DBMS_RLS.ADD_POLICY(
--     OBJECT_SCHEMA  => 'A01_QLNOIBO',
--     OBJECT_NAME  => 'V_PHANCONG_TD',
--     POLICY_NAME  => 'POL_V_PHANCONG_TD',
--     FUNCTION_SCHEMA  => 'A01_QLNOIBO',
--     POLICY_FUNCTION  => 'PFN_V_PHANCONG_TD',
--     STATEMENT_TYPES  => 'INSERT, DELETE, UPDATE',
--     UPDATE_CHECK => TRUE
-- ); END;
-- /

-- GRANT INSERT, DELETE, UPDATE ON V_PHANCONG_TD TO RL_A01_TD;

--      ---- CS5: TRUONG KHOA ----
-- CREATE OR REPLACE VIEW V_PHANCONG_TK
-- AS SELECT * FROM PHANCONG
--     WHERE MAHP IN (SELECT MAHP FROM HOCPHAN WHERE MADV = 1)
--     WITH CHECK OPTION;

-- GRANT SELECT, INSERT, DELETE, UPDATE ON V_PHANCONG_TK TO TK0001;

--      ---- CS6: SINH VIEN ----
-- CREATE OR REPLACE VIEW V_SINHVIEN_S
-- AS SELECT * FROM SINHVIEN;

-- CREATE OR REPLACE FUNCTION PFN_V_SINHVIEN_S(
--     P_SCHEMA VARCHAR2, P_OBJ VARCHAR2
-- ) RETURN VARCHAR2 AS BEGIN
--     RETURN 'MASV = ''' || SYS_CONTEXT('USERENV', 'SESSION_USER') || '''';
-- END;
-- /

-- BEGIN DBMS_RLS.ADD_POLICY(
--     OBJECT_SCHEMA  => 'A01_QLNOIBO',
--     OBJECT_NAME  => 'V_SINHVIEN_S',
--     POLICY_NAME  => 'POL_V_SINHVIEN_S',
--     FUNCTION_SCHEMA  => 'A01_QLNOIBO',
--     POLICY_FUNCTION  => 'PFN_V_SINHVIEN_S',
--     STATEMENT_TYPES  => 'SELECT, UPDATE',
--     UPDATE_CHECK => TRUE
-- ); END;
-- /

-- GRANT SELECT, UPDATE(DCHI, DT) ON V_SINHVIEN_S TO RL_A01_S;

--      ---- CS6: SINH VIEN ----
-- CREATE OR REPLACE VIEW V_KHMO_S
-- AS SELECT * FROM KHMO;

-- CREATE OR REPLACE FUNCTION PFN_V_KHMO_S(
--     P_SCHEMA VARCHAR2, P_OBJ VARCHAR2
-- ) RETURN VARCHAR2 AS BEGIN
--     RETURN 'MACT = ''' || (SELECT MACT FROM SINHVIEN
--         WHERE MASV = SYS_CONTEXT('USERENV', 'SESSION_USER')) || '''';
-- END;
-- /

-- BEGIN DBMS_RLS.ADD_POLICY(
--     OBJECT_SCHEMA  => 'A01_QLNOIBO',
--     OBJECT_NAME  => 'V_KHMO_S',
--     POLICY_NAME  => 'POL_V_KHMO_S',
--     FUNCTION_SCHEMA  => 'A01_QLNOIBO',
--     POLICY_FUNCTION  => 'PFN_V_KHMO_S',
--     STATEMENT_TYPES  => 'SELECT',
-- ); END;
-- /

-- GRANT SELECT ON HOCPHAN TO RL_A01_S;
-- GRANT SELECT ON V_KHMO_S TO RL_A01_S;

--      ---- CS6: SINH VIEN ----
-- CREATE OR REPLACE VIEW V_DANGKY_S
-- AS SELECT * FROM DANGKY;

-- ALTER SESSION SET CURRENT_SCHEMA = A01_QLNOIBO;
-- CREATE OR REPLACE FUNCTION PFN_V_DANGKY_S_INS_DEL(
--     P_SCHEMA VARCHAR2, P_OBJ VARCHAR2
-- ) RETURN VARCHAR2 AS
--     DIFF FLOAT; HK CHAR(1);
--     MO NUMBER(2) := TO_NUMBER(TO_CHAR(SYSDATE, 'MM'));
--     YE NUMBER(4) := TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'));
-- BEGIN
--     IF MO < 5 THEN HK := '1';
--         DIFF :=  SYSDATE - TO_DATE('01/01' || YE, 'DD/MM/YYYY');
--     ELSIF MO < 9 THEN HK := '2';
--         DIFF :=  SYSDATE - TO_DATE('01/05' || YE, 'DD/MM/YYYY');
--     ELSE HK := '3';
--         DIFF :=  SYSDATE - TO_DATE('01/09' || YE, 'DD/MM/YYYY');
--     END IF;
--     RETURN 'MASV = ''' || SYS_CONTEXT('USERENV', 'SESSION_USER')
--         || ''' AND HK = ' || HK || ' AND NAM = ' || YE
--         || 'AND 0 < ' || DIFF || ' AND ' || DIFF || '<= 14';
-- END;
-- /

-- BEGIN DBMS_RLS.ADD_POLICY(
--     OBJECT_SCHEMA  => 'A01_QLNOIBO',
--     OBJECT_NAME  => 'V_DANGKY_S_INS_DEL',
--     POLICY_NAME  => 'POL_V_DANGKY_S_INS_DEL',
--     FUNCTION_SCHEMA  => 'A01_QLNOIBO',
--     POLICY_FUNCTION  => 'PFN_V_DANGKY_S_INS_DEL',
--     STATEMENT_TYPES  => 'INSERT, DELETE',
--     UPDATE_CHECK => TRUE
-- ); END;
-- /

-- GRANT INSERT, DELETE ON PFN_V_DANGKY_S TO RL_A01_S;