CL SCR;

BEGIN
    EXECUTE IMMEDIATE 'DROP USER A01_QLNOIBO CASCADE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -1918 THEN RAISE;
    END IF;
END;
/

CREATE USER A01_QLNOIBO IDENTIFIED BY 123;
GRANT CREATE SESSION TO A01_QLNOIBO;
GRANT DBA TO A01_QLNOIBO;
ALTER SESSION SET CURRENT_SCHEMA = A01_QLNOIBO;

CREATE TABLE VAITRO (
    MAVT INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENVT VARCHAR2(50)
);

CREATE TABLE NHANSU (
    MANV VARCHAR2(6) PRIMARY KEY,
    HOTEN VARCHAR2(50),
    PHAI CHAR(1) DEFAULT '0',   -- '0': NAM, '1': NU
    NGSINH DATE,
    PHUCAP INT,
    DT VARCHAR2(11),            -- SO DIEN THOAI
    VAITRO INT,
    MADV INT,

    CONSTRAINT CHK_NHANSU_PHAI
    CHECK (PHAI IN ('0', '1')),

    CONSTRAINT FK_NHANSU_VAITRO
    FOREIGN KEY(VAITRO) REFERENCES VAITRO(MAVT)
    ON DELETE SET NULL
);

CREATE TABLE DONVI (
    MADV INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENDV VARCHAR2(50),
    TRGDV VARCHAR2(6) DEFAULT NULL,

    CONSTRAINT FK_DONVI_NHANSU
    FOREIGN KEY(TRGDV) REFERENCES NHANSU(MANV)
    ON DELETE SET NULL
);

ALTER TABLE NHANSU
ADD CONSTRAINT FK_NHANSU_DONVI
FOREIGN KEY(MADV) REFERENCES DONVI(MADV)
ON DELETE SET NULL;

CREATE TABLE CTDAOTAO (
    MACT VARCHAR2(6) PRIMARY KEY,
    TENCT VARCHAR2(50)
);

CREATE TABLE NGANH (
    MANGANH VARCHAR2(6) PRIMARY KEY,
    TENNGANH VARCHAR2(50)
);

CREATE TABLE SINHVIEN (
    MASV VARCHAR2(6) PRIMARY KEY,
    HOTEN VARCHAR2(50),
    PHAI CHAR(1) DEFAULT '0',   -- '0': NAM, '1': NU
    NGSINH DATE,
    DCHI VARCHAR2(100),         -- DIA CHI
    DT VARCHAR2(11),            -- SO DIEN THOAI
    MACT VARCHAR2(6),           -- MA CHUONG TRINH DAO TAO
    MANGANH VARCHAR2(6),
    SOTCTL INT,                 -- SO TIN CHI TICH LUY
    DTBTL FLOAT,                -- DIEM TRUNG BINH TICH LUY

    CONSTRAINT CHK_SINHVIEN_PHAI
    CHECK (PHAI IN ('0', '1')),

    CONSTRAINT FK_SINHVIEN_CTDAOTAO
    FOREIGN KEY(MACT) REFERENCES CTDAOTAO(MACT)
    ON DELETE SET NULL,

    CONSTRAINT FK_SINHVIEN_NGANH
    FOREIGN KEY(MANGANH) REFERENCES NGANH(MANGANH)
    ON DELETE SET NULL
);

CREATE TABLE HOCPHAN (
    MAHP VARCHAR2(6) PRIMARY KEY,
    TENHP VARCHAR2(50),
    SOTC INT,               -- SO TIN CHI
    STLT INT,               -- SO LOP LY THUYET
    STTH INT,               -- SO LOP THUC HANH
    SOSVTD INT,             -- SO SINH VIEN TOI DA
    MADV INT,

    CONSTRAINT FK_HOCPHAN_DONVI
    FOREIGN KEY(MADV) REFERENCES DONVI(MADV)
    ON DELETE SET NULL
);

CREATE TABLE KHMO (
    MAHP VARCHAR2(6),
    HK CHAR(1),             -- HOC KY
    NAM NUMBER(4),
    MACT VARCHAR2(6),       -- MA CHUONG TRINH DAO TAO

    CONSTRAINT CHK_KHMO_HK
    CHECK (HK IN ('1', '2', '3')),

    CONSTRAINT PK_KHMO
    PRIMARY KEY(MAHP, HK, NAM, MACT),

    CONSTRAINT FK_KHMO_HOCPHAN
    FOREIGN KEY(MAHP) REFERENCES HOCPHAN(MAHP)
    ON DELETE CASCADE,

    CONSTRAINT FK_KHMO_CTDAOTAO
    FOREIGN KEY(MACT) REFERENCES CTDAOTAO(MACT)
    ON DELETE CASCADE
);

CREATE TABLE PHANCONG (
    MAGV VARCHAR2(6),
    MAHP VARCHAR2(6),
    HK CHAR(1),             -- HOC KY
    NAM NUMBER(4),
    MACT VARCHAR2(6),       -- MA CHUONG TRINH DAO TAO

    CONSTRAINT PK_PHANCONG
    PRIMARY KEY(MAGV, MAHP, HK, NAM, MACT),

    CONSTRAINT FK_PHANCONG_NHANSU
    FOREIGN KEY(MAGV) REFERENCES NHANSU(MANV)
    ON DELETE CASCADE,

    CONSTRAINT FK_PHANCONG_KHMO
    FOREIGN KEY(MAHP, HK, NAM, MACT)
    REFERENCES KHMO(MAHP, HK, NAM, MACT)
    ON DELETE CASCADE
);

CREATE TABLE DANGKY (
    MASV VARCHAR2(6),
    MAGV VARCHAR2(6),
    MAHP VARCHAR2(6),
    HK CHAR(1),             -- HOC KY
    NAM NUMBER(4),
    MACT VARCHAR2(6),       -- MA CHUONG TRINH DAO TAO
    DIEMTH INT,             -- DIEM QUA TRINH
    DIEMQT INT,             -- DIEM THUC HANH
    DIEMCK INT,             -- DIEM CUOI KY
    DIEMTK INT,             -- DIEM TONG KET

    CONSTRAINT PK_DANGKY
    PRIMARY KEY(MASV, MAGV, MAHP, HK, NAM, MACT),

    CONSTRAINT FK_DANGKY_SINHVIEN
    FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV)
    ON DELETE CASCADE,

    CONSTRAINT FK_DANGKY_PHANCONG
    FOREIGN KEY(MAGV, MAHP, HK, NAM, MACT)
    REFERENCES PHANCONG(MAGV, MAHP, HK, NAM, MACT)
    ON DELETE CASCADE
);