CL SCR;

/* If a comment only contains a task's id but not its description then the
 *  code below it (until the next comment) are only helpers for the actual
 *  task. The former usually takes the form of "-- task)" while the latter
 *  a block comment with the task's description.
 * For example, below, the first one is helper and the second actual task.
 *  -- a)
 *      SELECT 100, 'A) TK', CHAR_TO_LABEL('...') FROM DUAL UNION ALL
 *  
 *  |* a) Hay gan nhan cho nguoi dung la Truong khoa co the doc duoc toan bo
 *   *  thong bao.
 *   *|
 *  BEGIN SA_USER_ADMIN.SET_USER_LABELS(
 *      POLICY_NAME  => 'POL_A01_THONGBAO',
 *      USER_NAME  => 'TK0001',
 *      MAX_READ_LABEL  => 'TK:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:DHX'
 *  ); END;
 */

-- HANDY FOR CHECKING
-- SELECT MATB, NOIDUNG, LABEL_TO_CHAR(LAB_TB) FROM A01_QLNOIBO.THONGBAO;

CONN AD0001/123@LOCALHOST/XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = A01_QLNOIBO;
GRANT SELECT ON THONGBAO TO PUBLIC;

BEGIN SA_SYSDBA.CREATE_POLICY(
    POLICY_NAME  => 'POL_A01_THONGBAO',
    COLUMN_NAME  => 'LAB_TB'
); END;
/

GRANT POL_A01_THONGBAO_DBA TO AD0001;
CONN AD0001/123@LOCALHOST/XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = A01_QLNOIBO;

BEGIN
    SA_COMPONENTS.CREATE_LEVEL(
        POLICY_NAME => 'POL_A01_THONGBAO',
        LEVEL_NUM => 9000,
        SHORT_NAME => 'TK',
        LONG_NAME => 'TRUONG KHOA'
    );
    SA_COMPONENTS.CREATE_LEVEL('POL_A01_THONGBAO', 8000, 'TD', 'TRUONG DON VI');
    SA_COMPONENTS.CREATE_LEVEL('POL_A01_THONGBAO', 7000, 'V', 'GIANG VIEN');
    SA_COMPONENTS.CREATE_LEVEL('POL_A01_THONGBAO', 6000, 'GV', 'GIAO VU');
    SA_COMPONENTS.CREATE_LEVEL('POL_A01_THONGBAO', 5000, 'NV', 'NHAN VIEN');
    SA_COMPONENTS.CREATE_LEVEL('POL_A01_THONGBAO', 4000, 'S', 'SINH VIEN');

    SA_COMPONENTS.CREATE_COMPARTMENT(
        POLICY_NAME  => 'POL_A01_THONGBAO',
        COMP_NUM  => 200,
        SHORT_NAME  => 'HTTT',
        LONG_NAME  => 'HE THONG THONG TIN'
    );
    SA_COMPONENTS.CREATE_COMPARTMENT('POL_A01_THONGBAO', 300, 'CNPM', 'CONG NGHE PHAN MEM');
    SA_COMPONENTS.CREATE_COMPARTMENT('POL_A01_THONGBAO', 400, 'KHMT', 'KHOA HOC MAY TINH');
    SA_COMPONENTS.CREATE_COMPARTMENT('POL_A01_THONGBAO', 500, 'CNTT', 'CONG NGHE TRI THUC');
    SA_COMPONENTS.CREATE_COMPARTMENT('POL_A01_THONGBAO', 600, 'TGMT', 'THI GIAC MAY TINH');
    SA_COMPONENTS.CREATE_COMPARTMENT('POL_A01_THONGBAO', 700, 'MMT', 'MANG MAY TINH VA VIEN THONG');

    SA_COMPONENTS.CREATE_GROUP(
        POLICY_NAME  => 'POL_A01_THONGBAO',
        GROUP_NUM  => 1000,
        SHORT_NAME  => 'DHX',
        LONG_NAME  => 'DAI HOC X',
        PARENT_NAME  => NULL
    );
    SA_COMPONENTS.CREATE_GROUP('POL_A01_THONGBAO', 1100, 'CS1', 'CO SO 1', 'DHX');
    SA_COMPONENTS.CREATE_GROUP('POL_A01_THONGBAO', 1200, 'CS2', 'CO SO 2', 'DHX');

/* LABEL_TAG = LEVEL_NUM + SUM(COMP_NUM)
 *              + (GROUP_NUM(DHX) * 10 IF DHX ELSE SUM(GROUP_NUM))
 * If duplicate, add 10 to the one that is semantically inferior.
 */
-- a)
    SA_LABEL_ADMIN.CREATE_LABEL(
        POLICY_NAME  => 'POL_A01_THONGBAO',
        LABEL_TAG  => '21700',
        LABEL_VALUE  => 'TK:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:DHX',
        DATA_LABEL  => TRUE
    );
-- b) and f)
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '18200', 'TD:HTTT:DHX');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '18300', 'TD:CNPM:DHX');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '18400', 'TD:KHMT:DHX');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '18500', 'TD:CNTT:DHX');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '18600', 'TD:TGMT:DHX');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '18710', 'TD:MMT:DHX');

    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '9300', 'TD:HTTT:CS1');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '9400', 'TD:HTTT:CS2');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '8200', 'TD:HTTT');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '9500', 'TD:KHMT:CS1');
-- c)
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '18700', 'GV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:DHX');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '7100', 'GV::CS1');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '8600', 'GV:CNPM:CS1,CS2');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '8100', 'GV:KHMT,CNTT:CS2');
-- d)
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '8000', 'TD');
-- e)
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '5300', 'S:HTTT:CS1');
-- g)
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '10700', 'TD:KHMT:CS1,CS2');
-- h1)
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '4000', 'S');
-- h2)
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '6100', 'NV::CS1');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '5510', 'S:CNPM:CS2');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '5500', 'S:KHMT:CS1');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '7400', 'NV:TGMT,MMT:CS1');
-- h3)
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '17700', 'NV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:DHX');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '6200', 'NV::CS2');
    SA_LABEL_ADMIN.CREATE_LABEL('POL_A01_THONGBAO', '6700', 'NV:CNTT:CS2');
END;
/

BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME  => 'POL_A01_THONGBAO',
        USER_NAME  => 'AD0001',
        MAX_READ_LABEL  => 'TK:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:DHX'
    );
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
        POLICY_NAME  => 'POL_A01_THONGBAO',
        SCHEMA_NAME  => 'A01_QLNOIBO',
        TABLE_NAME  => 'THONGBAO',
        TABLE_OPTIONS  => 'LABEL_DEFAULT,READ_CONTROL'
    );
END;
/

TRUNCATE TABLE THONGBAO;
INSERT INTO THONGBAO
-- a)
    SELECT 100, 'A) TK', CHAR_TO_LABEL('POL_A01_THONGBAO', 'TK:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:DHX') FROM DUAL UNION ALL
-- b)
    SELECT 200, 'B) TD HTTT CO SO 1', CHAR_TO_LABEL('POL_A01_THONGBAO', 'TD:HTTT:CS1') FROM DUAL UNION ALL
    SELECT 201, 'B1) TD HTTT CO SO 2', CHAR_TO_LABEL('POL_A01_THONGBAO', 'TD:HTTT:CS2') FROM DUAL UNION ALL
    SELECT 202, 'B2) TD HTTT', CHAR_TO_LABEL('POL_A01_THONGBAO', 'TD:HTTT') FROM DUAL UNION ALL
    SELECT 203, 'B3) TD KHMT CO SO 1', CHAR_TO_LABEL('POL_A01_THONGBAO', 'TD:KHMT:CS1') FROM DUAL UNION ALL
-- c)
    SELECT 300, 'C) GV CO SO 1', CHAR_TO_LABEL('POL_A01_THONGBAO', 'GV::CS1') FROM DUAL UNION ALL
    SELECT 301, 'C1) GV CNPM CO SO 1,2', CHAR_TO_LABEL('POL_A01_THONGBAO', 'GV:CNPM:CS1,CS2') FROM DUAL UNION ALL
    SELECT 302, 'C2) GV KHMT,CNTT CO SO 2', CHAR_TO_LABEL('POL_A01_THONGBAO', 'GV:KHMT,CNTT:CS2') FROM DUAL UNION ALL
/* d) Hay cho biet nhan cua dong thong bao t1 de t1 duoc phat tan (doc)
 *  boi tat ca Truong don vi. -- TD0007
 */
    SELECT 400, 'D) T1', CHAR_TO_LABEL('POL_A01_THONGBAO', 'TD') FROM DUAL UNION ALL
/* e) Hay cho biet nhan cua dong thong bao t2 de phat tan t2 den Sinh vien
 *  thuoc nganh HTTT hoc o Co so 1. -- S10001
 */
    SELECT 500, 'E) T2', CHAR_TO_LABEL('POL_A01_THONGBAO', 'S:HTTT:CS1') FROM DUAL UNION ALL
/* f) Hay cho biet nhan cua dong thong bao t3 de phat tan t3 den Truong bo
 *  mon KHMT o Co so 1. -- TD0003
 */
    SELECT 600, 'F) T3', CHAR_TO_LABEL('POL_A01_THONGBAO', 'TD:KHMT:CS1') FROM DUAL UNION ALL
/* g) Cho biet nhan cua dong thong bao t4 de phat tan t4 den Truong bo mon
 *  KHMT o Co so 1 va Co so 2. -- TD0009
 */
    SELECT 700, 'G) T4', CHAR_TO_LABEL('POL_A01_THONGBAO', 'TD:KHMT:CS1,CS2') FROM DUAL UNION ALL
/* h) Em hay cho them 3 chinh sach phat tan dong du lieu nua tren mo hinh
 *  OLS da cai dat.
 */
-- 1. Cho biet nhan cua thong bao phat tan den toan the sinh vien. -- S10001
    SELECT 800, 'H1) S', CHAR_TO_LABEL('POL_A01_THONGBAO', 'S') FROM DUAL UNION ALL
-- 2.
    SELECT 820, 'H2) S CNPM CS2', CHAR_TO_LABEL('POL_A01_THONGBAO', 'S:CNPM:CS2') FROM DUAL UNION ALL
    SELECT 821, 'H21) S KHMT CS1', CHAR_TO_LABEL('POL_A01_THONGBAO', 'S:KHMT:CS1') FROM DUAL UNION ALL
    SELECT 822, 'H22) NV TGMT,MMT CS1', CHAR_TO_LABEL('POL_A01_THONGBAO', 'NV:TGMT,MMT:CS1') FROM DUAL UNION ALL
    SELECT 823, 'H23) NV CS1', CHAR_TO_LABEL('POL_A01_THONGBAO', 'NV::CS1') FROM DUAL UNION ALL
-- 3.
    SELECT 830, 'H3) NV CS2', CHAR_TO_LABEL('POL_A01_THONGBAO', 'NV::CS2') FROM DUAL UNION ALL
    SELECT 831, 'H31) NV CNTT CS2', CHAR_TO_LABEL('POL_A01_THONGBAO', 'NV:CNTT:CS2') FROM DUAL;

/* a) Hay gan nhan cho nguoi dung la Truong khoa co the doc duoc toan bo
 *  thong bao. -- TK0001 or AD0001
 */
BEGIN SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME  => 'POL_A01_THONGBAO',
        USER_NAME  => 'TK0001',
        MAX_READ_LABEL  => 'TK:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:DHX'
); END;
/

/* b) Hay gan nhan cho cac Truong bo mon phu trach Co so 2 co the doc duoc
 *  toan bo thong bao danh cho truong bo mon khong phan biet vi tri dia ly.
 * -- TD0007
 */
DECLARE CUR SYS_REFCURSOR; USR VARCHAR2(6); DV INT; BM VARCHAR2(6);
BEGIN
    OPEN CUR FOR 'SELECT MANV, MADV FROM NHANSU WHERE VAITRO = 4 AND MACS = 2';
    LOOP FETCH CUR INTO USR, DV;
        EXIT WHEN CUR%NOTFOUND;
        SELECT TRIM(SUBSTR(TENDV, 8, 4)) INTO BM FROM DONVI WHERE MADV = DV;
        SA_USER_ADMIN.SET_USER_LABELS(
            POLICY_NAME  => 'POL_A01_THONGBAO',
            USER_NAME  => USR,
            MAX_READ_LABEL  => 'TD:' || BM || ':DHX'
        );
    END LOOP; CLOSE CUR;
END;
/

/* c) Hay gan nhan cho 01 Giao vu co the doc toan bo thong bao danh cho
 *  giao vu. -- GV0001
 */
BEGIN SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME  => 'POL_A01_THONGBAO',
        USER_NAME  => 'GV0001',
        MAX_READ_LABEL  => 'GV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:DHX'
); END;
/

-- e)
DECLARE CUR SYS_REFCURSOR; USR VARCHAR2(6);
BEGIN
    OPEN CUR FOR 'SELECT MASV FROM SINHVIEN WHERE MANGANH = ''HTTT'' AND MACS = 1';
    LOOP FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        SA_USER_ADMIN.SET_USER_LABELS(
            POLICY_NAME  => 'POL_A01_THONGBAO',
            USER_NAME  => USR,
            MAX_READ_LABEL  => 'S:HTTT:CS1'
        );
    END LOOP; CLOSE CUR;
END;
/

-- f)
DECLARE CUR SYS_REFCURSOR; USR VARCHAR2(6);
BEGIN
    OPEN CUR FOR 'SELECT MANV FROM NHANSU '
        || 'WHERE VAITRO = 4 AND MADV = 4 AND MACS = 1';
    LOOP FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        SA_USER_ADMIN.SET_USER_LABELS(
            POLICY_NAME  => 'POL_A01_THONGBAO',
            USER_NAME  => USR,
            MAX_READ_LABEL  => 'TD:KHMT:CS1'
        );
    END LOOP; CLOSE CUR;
END;
/

/* h) Em hay cho them 3 chinh sach phat tan dong du lieu nua tren mo hinh
 *  OLS da cai dat.
 */
-- 2. Gan nhan cho nhan vien co so 1 chi duoc xem thong bao khong co chu
--  de (khong thuoc ve bo mon cu the) cua co so 1. -- NV0001
DECLARE CUR SYS_REFCURSOR; USR VARCHAR2(6);
BEGIN
    OPEN CUR FOR 'SELECT MANV FROM NHANSU WHERE VAITRO = 1 AND MACS = 1';
    LOOP FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        SA_USER_ADMIN.SET_USER_LABELS(
            POLICY_NAME  => 'POL_A01_THONGBAO',
            USER_NAME  => USR,
            MAX_READ_LABEL  => 'NV::CS1'
        );
    END LOOP; CLOSE CUR;
END;
/

-- 3. Gan nhan cho 1 nhan vien co so 2 co the xem moi thong bao cho nhan
--  vien (khong gioi han chu de va co so). -- NV0006
BEGIN SA_USER_ADMIN.SET_USER_LABELS(
    POLICY_NAME  => 'POL_A01_THONGBAO',
    USER_NAME  => 'NV0006',
    MAX_READ_LABEL  => 'NV:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:DHX'
); END;
/