CL SCR;
ALTER SESSION SET CURRENT_SCHEMA = A01_QLNOIBO;

CREATE USER AD0001 IDENTIFIED BY 123;
GRANT CREATE SESSION TO AD0001;
GRANT DBA TO AD0001;

CREATE OR REPLACE PROCEDURE USP_CREATE_USERS
AS
    CURSOR CUR_NHANSU IS (SELECT MANV FROM NHANSU
        WHERE MANV NOT IN (SELECT USERNAME FROM ALL_USERS));
    CURSOR CUR_SINHVIEN IS (SELECT MASV FROM SINHVIEN
        WHERE MASV NOT IN (SELECT USERNAME FROM ALL_USERS));
BEGIN
    FOR USR IN CUR_NHANSU LOOP
        EXECUTE IMMEDIATE 'CREATE USER ' || USR.MANV || ' IDENTIFIED BY 123';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || USR.MANV;
    END LOOP;
    FOR USR IN CUR_SINHVIEN LOOP
        EXECUTE IMMEDIATE 'CREATE USER ' || USR.MASV || ' IDENTIFIED BY 123';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || USR.MASV;
    END LOOP;
END;
/
EXEC USP_CREATE_USERS();